---
title       : Lending Club 2014 Note Data Explorer
subtitle    : Coursera Data Products August 2015 - Coure Project
author      : Matthew Landowski
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap]   # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
url:
  lib   : libraries
  assets: assets
knit        : slidify::knit2slides
---

## Lending Club Note Explorer ##

The application is hosted on [shinyapps.io](https://washcycle.shinyapps.io/2014_lending_club_note_explorer), click the link to open the applicaiton. A note is a loan. Lending club is a peer-to-peer personnel loan lender, notes can be funded by individuals and/or instituions.

--- .class #id 

## The Goal ##
1. Explorer the data set to determine variables that help making investing decisions.
2. Calculate distributions for different note loan issuing variables.
3. For each variable into charged-off(defaulted) and fully paid notes.

--- .class #id 

## Variables ##

List of all the currently availbe variables that will work with the data explorer.

| Variable | Definition |
| -------- | ---------- |
| loan_amnt | loan amount in dollars |
| int_rate | interest rate on loan |
| installment | monthly payment amount in dollars |
| annual_inc | anual income in dollars |
| dti | Debt-to-income ratio |
| fico_range_low | fico score low |
| fico_range_high | ficoe score high |
| revol_bal | revolving credit balance in dollars |
| revol_util | revolving credit utilization ratio |
| total_acc | total credit accounts |

--- .class #id &twocol

## How to Use Results ##

*** =left

Looking at the distribution for a variable to get an idea of at what value a fully paid note is likley to happen vs a charged-off note.

A high desntiy of fully paid vs charged-off notes would signifiy a variable that might be worth investigating further. 

Example: The figure on the right shows the debt-to-income(dti) ratio for a borrower. The fully paid notes are shifted to the left with respect to the charged off notes. This means that lower dti increases the likely hood that a note will be fully paid.

*** =right

```{r, echo = F}
library(ggplot2)
load("notes_fully_charged_full_paid.RData")
ggplot(data = notes_charged_full_paid, aes(x = dti, color = loan_status)) +
    geom_density(aes(y=..density.., fill = loan_status), alpha = 0.2) +
    ggtitle("Debt-to-Income with Respect to Loan Status")
```
